"""Initial schema

Revision ID: 03b69e5d573c
Revises: 
Create Date: 2026-05-09 17:30:21.367125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03b69e5d573c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_access_course_id_fkey'), 'course_access', type_='foreignkey')
    op.drop_constraint(op.f('course_access_student_id_fkey'), 'course_access', type_='foreignkey')
    op.create_foreign_key(None, 'course_access', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_access', 'users', ['student_id'], ['id'])
    op.alter_column('courses', 'icon',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('courses', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('courses', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'lesson'::character varying"))
    op.drop_constraint(op.f('courses_author_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['author_id'], ['id'])
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'choice'::character varying"))
    op.alter_column('questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('questions', 'explanation',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('results', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Курсант'::character varying"))
    op.alter_column('results', 'passed',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('student_lectures_view_student_id_course_id_key'), 'student_lectures_view', type_='unique')
    op.drop_constraint(op.f('student_lectures_view_course_id_fkey'), 'student_lectures_view', type_='foreignkey')
    op.drop_constraint(op.f('student_lectures_view_student_id_fkey'), 'student_lectures_view', type_='foreignkey')
    op.create_foreign_key(None, 'student_lectures_view', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'student_lectures_view', 'users', ['student_id'], ['id'])
    op.alter_column('system_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'is_blocked',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('system_logs', 'details',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'student_lectures_view', type_='foreignkey')
    op.drop_constraint(None, 'student_lectures_view', type_='foreignkey')
    op.create_foreign_key(op.f('student_lectures_view_student_id_fkey'), 'student_lectures_view', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_lectures_view_course_id_fkey'), 'student_lectures_view', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('student_lectures_view_student_id_course_id_key'), 'student_lectures_view', ['student_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('results', 'passed',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('results', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Курсант'::character varying"))
    op.alter_column('questions', 'explanation',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'choice'::character varying"))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_author_id_fkey'), 'courses', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('courses', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'lesson'::character varying"))
    op.alter_column('courses', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'icon',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'course_access', type_='foreignkey')
    op.drop_constraint(None, 'course_access', type_='foreignkey')
    op.create_foreign_key(op.f('course_access_student_id_fkey'), 'course_access', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('course_access_course_id_fkey'), 'course_access', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
